Stress test outcome
elastic/elastic-serverless-forwarder pull request #48
Opened 2021-12-14 19:05 UTC by aspacca

Enhancement

## What does this PR do?

Address performance issues emerged during stress testing the lambda

## Why is it important?
We reduce that change of failure and missing ingestions with a proper scaled cluster

## Checklist

- [x] My code follows the style guidelines of this project
~- [ ] I have commented my code, particularly in hard-to-understand areas~
~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have made corresponding change to the default configuration files~
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.md`

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Use cases

## Screenshots

## Logs

2021-12-14 19:25 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Library%2Felastic-serverless-forwarder-mbp%2FPR-48/detail/PR-48/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Library%2Felastic-serverless-forwarder-mbp%2FPR-48/detail/PR-48/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Library%2Felastic-serverless-forwarder-mbp%2FPR-48/detail/PR-48/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Library%2Felastic-serverless-forwarder-mbp%2FPR-48/detail/PR-48/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://elastic-serverless-forwarder_48.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-12-14T18:55:51.475Z&rangeTo=2021-12-14T19:15:51.475Z&transactionName=Library%2Felastic-serverless-forwarder-mbp%2FPR-%7Bnumber%7D&transactionType=unknown&latencyAggregationType=avg&traceId=2288d55243336af26535b15e56765434&transactionId=0346a3d9d32be7e4)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-12-14T19:05:51.475+0000


* Duration: 20 min 42 sec


* Commit: 84b0c03d52fd79b4b540da6ed491f3e6249e3fc5



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 30  |
| Skipped      | 0 |
| Total        | 30   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-12-15 11:50 UTC, endorama requested changes
Just a minor wording enhancement and a request: could you add to fafa0612c99330c0c1494913c3566f30af328a30 commit message some details about the change? I think they are very meaningful and merit to be added to the history for future reference.

2021-12-15 11:50 UTC, endorama commented on CHANGELOG.md
> +* General performance refactoring as stress test outcome: [#48](https://github.com/elastic/elastic-serverless-forwarder/pull/48)
```suggestion
* General performance refactoring after stress test outcome: [#48](https://github.com/elastic/elastic-serverless-forwarder/pull/48)
```

2021-12-15 11:58 UTC, aspacca commented
> could you add to fafa061 commit message some details about the change?

reworded as https://github.com/elastic/elastic-serverless-forwarder/pull/48/commits/a0dfb687eeb21fad2aae8752e8c63591f928e451

2021-12-15 14:22 UTC, aspacca commented
@endorama fixed

2021-12-16 12:01 UTC, endorama commented
I've just a question around lambda RAM limits. Does it mean that if I have a file larger than max Lambda memory I cannot ingest it directly into Elastic, but it requires to be split in smaller chunks? Just for clarity, with the current 10GB RAM limit I don't this as a concern

2021-12-16 12:01 UTC, endorama approved these changes

2021-12-16 12:05 UTC, aspacca commented
> Does it mean that if I have a file larger than max Lambda memory I cannot ingest it directly into Elastic, but it requires to be split in smaller chunks?

that's correct, we could further improve and according to the length of the file given by the `head_object` request we can decide if using `get_object` with the eventual connection reset that we should find a way to handle, or `donwload_fileobj` in the current optimisation

2021-12-16 12:06 UTC, merged